spring:
  datasource:
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:log4jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    jdbcUrl: ${spring.datasource.url}
    username: sa
    password:
  hikari:
    minimum-idle: 5
    maximum-pool-size: 30
  h2:
    console:
      enabled: true
  r2dbc:
    pool:
      enabled: true
      initialSize: 5
      maxSize: 30

logging:
  level: 
    jdbc.sqlonly: OFF
    org.springframework.web: OFF
    com.zaxxer.hikari: OFF
    io.r2dbc.pool: OFF
